{% set name = "datapane" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6b44cc18df4b4bfd2f39d9220aafcfad7aed82e330d2af44817847e8bbaf41c5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8.0,<4.0.0
    - pip
    - setuptools
    - poetry >=1.3.1,<1.5.0
  run:
    - python >=3.8.0,<3.12.0

    # DS
    - pandas >=1.4.0,<2.0.0
    - pyarrow >=9.0.0

    # viz
    - altair >=5.0.0,<6.0.0
    - vega_datasets >=0.9.0,<1.0.0

    # misc
    - chardet >=5.0.0,<6.0.0
    - colorlog >=6.4.0,<7.0.0
    - dominate >=2.7.0,<3.0.0
    - importlib_resources >=5.6.0
    - lxml >=4.7.0,<5.0.0
    - micawber >=0.5.3
    - packaging >=21.0.0,<24.0.0
    - ipynbname >=2021.3.2
    - multimethod >=1.9.0,<2.0.0
    - typing_extensions >=4.4.0,<5.0.0

  run_constrained:
    # extra viz
    - matplotlib-base >=3.5.0,<4.0.0
    - plotly >=5.6.0,<6.0.0
    - bokeh >=2.3.0,<3.0.0
    - folium >=0.13.0,<0.15.0

test:
  imports:
    - datapane
    - datapane.client
    - datapane.common
    - datapane.view
    - datapane.resources
  requires:
    - pip
#  commands:
#    - pip check

about:
  home: https://datapane.com
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Datapane client library and CLI tool
  description: |
    Create and publish interactive reports and apps in Python. 
    Datapane is an open source framework which makes 
    it easy to turn scripts and notebooks into interactive reports and apps. 
  doc_url: https://docs.datapane.com/
  dev_url: https://github.com/datapane/datapane

extra:
  recipe-maintainers:
    - mands
