{% set name = "datapane" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03fc55a9524a53f420d6db614396a17ada2847931abed8d9c427b21d885ecf9d

build:
  noarch: python
  number: 0
  entry_points:
    - datapane = datapane.client.__main__:main
    - dp-runner = datapane.runner.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7.0,<4.0.0
    - pip
    - setuptools
    - poetry >=1.0.0,<2.0.0
  run:
    - python >=3.7.0,<4.0.0

    # DS
    - pandas >=1.0.1,<2.0.0
    - pyarrow >=3.0.0,<4.0.0

    # viz
    - altair >=4.0.0,<5.0.0

    # misc
    - dacite >=1.5.0,<2.0.0
    - colorlog >=4.0.2,<5.0.0
    - munch >=2.3.0,<3.0.0
    - stringcase >=1.2.0,<2.0.0
    - pyyaml >=5.1.0,<6.0.0
    - packaging >=20.0,<21.0

    # cli
    - click >=7.0.0,<8.0.0
    - click-spinner >=0.1.8,<0.2.0
    - requests >=2.19.0,<3.0.0
    - validators >=0.17.1,<0.19.0
    - jinja2 >=2.10.0,<3.0.0
    - jsonschema >=3.0.0,<4.0.0
    - tabulate >=0.8.0,<0.9.0
    - toolz >=0.11.0,<0.12.0
    - importlib_resources >=3.0.0,<6.0.0
    - lxml >=4.0.0,<5.0.0
    - requests-toolbelt >=0.9.1,<0.10.0
    - furl >=2.0.0,<3.0.0
    - bleach >=3.0.2,<4.0.0
    - glom >=20.5.0,<21.0.0
    - boltons >=20.0.0,<21.0.0
    - dominate >=2.4.0,<3.0.0
    - micawber >=0.5.0,<0.6.0
  run_constrained:
    # extra viz
    - matplotlib-base >=3.0.0,<4.0.0
    # - bokeh >=2.0.0,<3.0.0
    - bokeh >=2.2.0,<2.3.0
    - plotly >=4.0.0,<5.0.0
    - folium >=0.12.0,<0.13.0
    # cloud - TODO - make into metapackage
    - nbconvert >=6.0.0,<6.1.0
    - flit-core >=3.0.0,<3.1.0  

test:
  imports:
    - datapane
    - datapane.client
    - datapane.client.api
    - datapane.client.scripts
    - datapane.common
    - datapane.resources
    - datapane.resources.local_report
    - datapane.resources.templates
    - datapane.runner
  commands:
    - datapane --help
    - datapane --version
    - dp-runner --help
  requires:
    - pip
#  commands:
#    - pip check

about:
  home: https://datapane.com
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Datapane client library and CLI tool
  description: |
    Create and publish interactive reports in Python. 
    Datapane is an open source framework which makes 
    it easy to turn scripts and notebooks into interactive reports. 
  doc_url: https://docs.datapane.com/
  dev_url: https://github.com/datapane/datapane

extra:
  recipe-maintainers:
    - mands
