{% set name = "datapane" %}
{% set version = "0.16.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e23b6efe64d70b59a4c4083461479409bb48f0a0bfcec9b74d4a0ced853c7622

build:
  noarch: python
  number: 0
  entry_points:
    - datapane = datapane.client.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8.0,<3.12.0
    - pip
    - setuptools
    - poetry >=1.3.1,<1.5.0
  run:
    - python >=3.8.0,<3.12.0

    # DS
    - pandas >=1.1.0,<2.0.0
    - pyarrow >=6.0.0,<11.0.0

    # viz
    - altair >=4.0.0,<5.0.0
    - vega_datasets >=0.9.0,<1.0.0

    # misc
    - boltons >=20.0.0,<22.0.0
    - chardet >=4.0.0,<6.0.0
    - click >=7.1.0,<9.0.0
    - click-spinner >=0.1.8,<0.2.0
    - colorlog >=4.1.0,<7.0.0
    - dacite >=1.0.2,<2.0.0
    # waiting for release to conda-forge
    #- datacommons >=1.4.3,<2.0.0
    #- datacommons-pandas = >=0.0.3,<0.1.0
    - dominate >=2.4.0,<3.0.0
    - dulwich >=0.20.0,<0.22.0
    - furl >=2.0.0,<3.0.0
    - glom >=22.1.0,<24.0.0
    - importlib_resources >=3.0.0,<6.0.0
    - jsonschema >=3.2.0,<5.0.0
    - lxml >=4.0.0,<5.0.0
    - micawber >=0.5.0
    - nbconvert >=6.1.0,<8.0.0
    - packaging >=21.0.0,<24.0.0
    - posthog >=1.4.0,<3.0.0
    - pydantic >=1.6.0,<2.0.0
    - pyyaml >=5.4.0,<7.0.0
    - requests >=2.19.0,<3.0.0
    - requests-toolbelt >=0.9.1,<1.1.0
    - tabulate >=0.8.9,<0.10.0
    - toolz >=0.11.0,<0.13.0
    - ipynbname >=2021.3.2,<2023.0.0
    - cheroot >=9.0.0,<10.0.0
    - multimethod >=1.9.0,<2.0.0
    - typing_extensions >=4.0.0,<5.0.0
    - pyngrok >=5.2.1,<6.0.0

  run_constrained:
    # extra viz
    - matplotlib-base >=3.2.0,<4.0.0
    - plotly >=5.0.0,<6.0.0
    - bokeh >=2.3.0,<3.0.0
    - folium >=0.12.0,<0.15.0
    - plotapi >=6.0.0,<7.0.0
    # cloud - TODO - make into metapackage
    - flit-core >=3.1.0,<4.0.0

test:
  imports:
    - datapane
    - datapane.client
    - datapane.common
    - datapane.app
    - datapane.view
    - datapane.resources
  commands:
    - datapane --help
    - datapane --version
  requires:
    - pip
#  commands:
#    - pip check

about:
  home: https://datapane.com
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Datapane client library and CLI tool
  description: |
    Create and publish interactive reports and apps in Python. 
    Datapane is an open source framework which makes 
    it easy to turn scripts and notebooks into interactive reports and apps. 
  doc_url: https://docs.datapane.com/
  dev_url: https://github.com/datapane/datapane

extra:
  recipe-maintainers:
    - mands
    - shahinrostami
