{% set name = "datapane" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a395095c4dd24e2b68510179ab47ba8a33f78f2c82bcad7c3b42f83624bed136

build:
  noarch: python
  number: 0
  entry_points:
    - datapane = datapane.client.__main__:main
    - dp-runner = datapane.runner.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6.1,<4.0.0
    - pip
    - setuptools
    - poetry >=1.0.0,<2.0.0
  run:
    - python >=3.6.1,<4.0.0
    - dataclasses >=0.7.0,<0.8.0

    # DS
    - numpy >=1.18.0,<2.0.0
    - pandas >=1.0.1,<2.0.0
    - pyarrow >=2.0.0,<3.0.0

    # viz
    - matplotlib-base >=3.1.0,<4.0.0
    - altair >=4.0.0,<5.0.0
    # - bokeh >=2.0.0,<3.0.0
    - bokeh >=2.0.0,<2.0.1
    - nbconvert >=6.0.0,<6.1.0
    - plotly >=4.8.1,<5.0.0
    - folium >=0.11.0,<0.12.0

    # misc
    - dacite >=1.5.0,<2.0.0
    - colorlog >=4.1.0,<5.0.0
    - munch >=2.5.0,<3.0.0
    - stringcase >=1.2.0,<2.0.0
    - pyyaml >=5.3.0,<6.0.0
    - packaging >=20.3,<21.0

    # cli
    - click >=7.0.0,<8.0.0
    - click-spinner >=0.1.8,<0.2.0
    - ruamel.yaml >=0.16.5,<0.17.0
    - requests >=2.20.0,<3.0.0
    - validators >=0.18.0,<0.19.0
    - jinja2 >=2.11.1,<3.0.0
    - jsonschema >=3.2.0,<4.0.0
    - tabulate >=0.8.7,<0.9.0
    - toolz >=0.11.0,<0.12.0
    - flit-core >=3.0.0,<3.1.0
    - importlib_resources >=3.0.0,<4.0.0
    - lxml >=4.5.2,<5.0.0
    - requests-toolbelt >=0.9.1,<0.10.0
    - furl >=2.1.0,<3.0.0
    - bleach >=3.2.1,<4.0.0
    - glom >=20.11.0,<21.0.0
    - boltons >=20.2.1,<21.0.0
    - dominate >=2.4.0,<3.0.0
    - micawber >= 0.5.0,<0.6.0


test:
  imports:
    - datapane
    - datapane.client
    - datapane.client.api
    - datapane.client.scripts
    - datapane.common
    - datapane.resources
    - datapane.resources.local_report
    - datapane.resources.templates
    - datapane.runner
  commands:
    - datapane --help
    - datapane --version
    - dp-runner --help
  requires:
    - pip
#  commands:
#    - pip check

about:
  home: https://datapane.com
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Datapane client library and CLI tool
  description: |
    Create and publish interactive reports in Python. 
    Datapane is an open source framework which makes 
    it easy to turn scripts and notebooks into interactive reports. 
  doc_url: https://docs.datapane.com/
  dev_url: https://github.com/datapane/datapane

extra:
  recipe-maintainers:
    - mands
